[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

[window]
blur = true
opacity = 1

[font]
normal = { family = "0xProto Nerd Font Mono", style = "normal" }
size = 14

[selection]
save_to_clipboard = true